# Generated by Django 4.2 on 2023-04-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="appuser", options={},),
    ]
