# Generated by Django 4.2 on 2023-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_appuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
