# Generated by Django 4.2 on 2023-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_appuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportedCrimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("record_time", models.DateTimeField(auto_now=True)),
                ("report_time", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("crimetype", models.CharField(max_length=30, null=True)),
                ("description", models.TextField(null=True)),
                ("image", models.ImageField(upload_to="media/images")),
                ("gender", models.CharField(max_length=10)),
                ("audio", models.FileField(upload_to="media/audio")),
                ("platform", models.CharField(default="mobile", max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="appuser",
            name="platform",
            field=models.CharField(default="website", max_length=10),
        ),
    ]
