# Generated by Django 4.2 on 2023-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_reportedcrimes_appuser_platform"),
    ]

    operations = [
        migrations.RemoveField(model_name="reportedcrimes", name="report_time",),
        migrations.AddField(
            model_name="reportedcrimes",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reportedcrimes",
            name="audio",
            field=models.FileField(null=True, upload_to="media/audio"),
        ),
        migrations.AlterField(
            model_name="reportedcrimes",
            name="image",
            field=models.ImageField(null=True, upload_to="media/images"),
        ),
    ]
