# Generated by Django 4.2 on 2023-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_reportedcrimes_report_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="gender",
            field=models.CharField(default="male", max_length=20),
        ),
    ]
