# Generated by Django 4.2 on 2023-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_reportedcrimes_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportedcrimes",
            name="audio",
            field=models.FileField(null=True, upload_to="media/Audio"),
        ),
    ]
