# Generated by Django 4.2 on 2023-04-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_reportedcrimes_audio"),
    ]

    operations = [
        migrations.RemoveField(model_name="appuser", name="gender",),
    ]
