# Generated by Django 4.2 on 2023-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_appuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="gender",
            field=models.CharField(default="male", max_length=20),
        ),
    ]
