# Generated by Django 4.2 on 2023-04-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shapes", "0002_alter_counties_2021_breakings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counties_2021", options={"verbose_name_plural": "Counties_2021"},
        ),
    ]
